"""Initial schema baseline

Revision ID: 6a1721321edd
Revises: 
Create Date: 2026-09-04 16:58:58.401934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1721321edd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_lines',
    sa.Column('cell_line_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tissue_origin', sa.String(length=128), nullable=True),
    sa.Column('cancer_type', sa.String(length=128), nullable=True),
    sa.Column('disease', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cell_line_id')
    )
    op.create_index(op.f('ix_cell_lines_cancer_type'), 'cell_lines', ['cancer_type'], unique=False)
    op.create_index(op.f('ix_cell_lines_cell_line_id'), 'cell_lines', ['cell_line_id'], unique=False)
    op.create_index(op.f('ix_cell_lines_name'), 'cell_lines', ['name'], unique=False)
    op.create_table('compounds',
    sa.Column('compound_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_smiles', sa.Text(), nullable=False),
    sa.Column('isomeric_smiles', sa.Text(), nullable=True),
    sa.Column('inchikey', sa.String(length=27), nullable=False),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('molecular_formula', sa.String(length=128), nullable=False),
    sa.Column('molecular_weight', sa.Float(), nullable=False),
    sa.Column('exact_mass', sa.Float(), nullable=True),
    sa.Column('heavy_atom_count', sa.Integer(), nullable=False),
    sa.Column('formal_charge', sa.Integer(), nullable=False),
    sa.Column('murcko_scaffold_smiles', sa.Text(), nullable=True),
    sa.Column('has_stereochemistry', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('processing_version', sa.String(length=64), nullable=False),
    sa.Column('rdkit_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('compound_id')
    )
    op.create_index(op.f('ix_compounds_canonical_smiles'), 'compounds', ['canonical_smiles'], unique=False)
    op.create_index(op.f('ix_compounds_compound_id'), 'compounds', ['compound_id'], unique=False)
    op.create_index(op.f('ix_compounds_has_stereochemistry'), 'compounds', ['has_stereochemistry'], unique=False)
    op.create_index(op.f('ix_compounds_inchikey'), 'compounds', ['inchikey'], unique=True)
    op.create_index(op.f('ix_compounds_molecular_formula'), 'compounds', ['molecular_formula'], unique=False)
    op.create_index(op.f('ix_compounds_molecular_weight'), 'compounds', ['molecular_weight'], unique=False)
    op.create_index(op.f('ix_compounds_murcko_scaffold_smiles'), 'compounds', ['murcko_scaffold_smiles'], unique=False)
    op.create_index(op.f('ix_compounds_tenant_id'), 'compounds', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('input_params_json', sa.Text(), nullable=True),
    sa.Column('result_summary_json', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('organisms',
    sa.Column('organism_id', sa.String(length=64), nullable=False),
    sa.Column('scientific_name', sa.String(length=256), nullable=False),
    sa.Column('common_name', sa.String(length=128), nullable=True),
    sa.Column('ncbi_taxonomy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('organism_id')
    )
    op.create_index(op.f('ix_organisms_scientific_name'), 'organisms', ['scientific_name'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('homepage_url', sa.String(length=512), nullable=True),
    sa.Column('license_name', sa.String(length=128), nullable=True),
    sa.Column('license_terms', sa.Text(), nullable=True),
    sa.Column('is_commercial_allowed', sa.Boolean(), nullable=False),
    sa.Column('acquisition_method', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('chemical_structures',
    sa.Column('compound_id', sa.String(length=64), nullable=False),
    sa.Column('num_rings', sa.Integer(), nullable=False),
    sa.Column('num_aromatic_rings', sa.Integer(), nullable=False),
    sa.Column('num_aliphatic_rings', sa.Integer(), nullable=False),
    sa.Column('num_chiral_centers', sa.Integer(), nullable=False),
    sa.Column('num_defined_chiral_centers', sa.Integer(), nullable=False),
    sa.Column('num_undefined_chiral_centers', sa.Integer(), nullable=False),
    sa.Column('is_salt', sa.Boolean(), nullable=False),
    sa.Column('salt_fragment_smiles', sa.Text(), nullable=True),
    sa.Column('parent_compound_smiles', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.compound_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('compound_id')
    )
    op.create_table('compound_identifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('compound_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('identifier_type', sa.String(length=64), nullable=False),
    sa.Column('identifier_value', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.compound_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compound_identifiers_compound_id'), 'compound_identifiers', ['compound_id'], unique=False)
    op.create_index(op.f('ix_compound_identifiers_identifier_type'), 'compound_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_compound_identifiers_identifier_value'), 'compound_identifiers', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_compound_identifiers_tenant_id'), 'compound_identifiers', ['tenant_id'], unique=False)
    op.create_index('ix_identifier_type_value', 'compound_identifiers', ['identifier_type', 'identifier_value'], unique=False)
    op.create_table('datasets',
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_datasets_source_id'), 'datasets', ['source_id'], unique=False)
    op.create_index(op.f('ix_datasets_tenant_id'), 'datasets', ['tenant_id'], unique=False)
    op.create_table('molecular_features',
    sa.Column('compound_id', sa.String(length=64), nullable=False),
    sa.Column('clogp', sa.Float(), nullable=False),
    sa.Column('tpsa', sa.Float(), nullable=False),
    sa.Column('hbd', sa.Integer(), nullable=False),
    sa.Column('hba', sa.Integer(), nullable=False),
    sa.Column('rotatable_bonds', sa.Integer(), nullable=False),
    sa.Column('fraction_csp3', sa.Float(), nullable=False),
    sa.Column('morgan_fp_2048_hex', sa.Text(), nullable=False),
    sa.Column('fingerprint_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.compound_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('compound_id')
    )
    op.create_index(op.f('ix_molecular_features_clogp'), 'molecular_features', ['clogp'], unique=False)
    op.create_index(op.f('ix_molecular_features_tpsa'), 'molecular_features', ['tpsa'], unique=False)
    op.create_table('targets',
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('target_name', sa.String(length=256), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('uniprot_id', sa.String(length=32), nullable=True),
    sa.Column('gene_symbol', sa.String(length=64), nullable=True),
    sa.Column('organism_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.organism_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_index(op.f('ix_targets_gene_symbol'), 'targets', ['gene_symbol'], unique=False)
    op.create_index(op.f('ix_targets_target_id'), 'targets', ['target_id'], unique=False)
    op.create_index(op.f('ix_targets_target_name'), 'targets', ['target_name'], unique=False)
    op.create_index(op.f('ix_targets_uniprot_id'), 'targets', ['uniprot_id'], unique=False)
    op.create_table('assays',
    sa.Column('assay_id', sa.String(length=64), nullable=False),
    sa.Column('assay_name', sa.String(length=256), nullable=False),
    sa.Column('assay_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('cell_line_id', sa.String(length=64), nullable=True),
    sa.Column('organism_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('curation_status', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cell_line_id'], ['cell_lines.cell_line_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.organism_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.target_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('assay_id')
    )
    op.create_index(op.f('ix_assays_assay_id'), 'assays', ['assay_id'], unique=False)
    op.create_index(op.f('ix_assays_assay_type'), 'assays', ['assay_type'], unique=False)
    op.create_index(op.f('ix_assays_cell_line_id'), 'assays', ['cell_line_id'], unique=False)
    op.create_index(op.f('ix_assays_target_id'), 'assays', ['target_id'], unique=False)
    op.create_index(op.f('ix_assays_tenant_id'), 'assays', ['tenant_id'], unique=False)
    op.create_table('processing_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('rdkit_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('valid_records', sa.Integer(), nullable=False),
    sa.Column('rejected_records', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_processing_runs_dataset_id'), 'processing_runs', ['dataset_id'], unique=False)
    op.create_table('source_records',
    sa.Column('source_record_id', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('raw_payload_uri', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_structure_string', sa.Text(), nullable=True),
    sa.Column('compound_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.compound_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.dataset_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_record_id'),
    sa.UniqueConstraint('dataset_id', 'external_id', name='uq_source_records_dataset_external')
    )
    op.create_index('ix_source_external_id', 'source_records', ['source_id', 'external_id'], unique=False)
    op.create_index(op.f('ix_source_records_compound_id'), 'source_records', ['compound_id'], unique=False)
    op.create_index(op.f('ix_source_records_content_hash'), 'source_records', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_records_dataset_id'), 'source_records', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_source_records_external_id'), 'source_records', ['external_id'], unique=False)
    op.create_index(op.f('ix_source_records_source_id'), 'source_records', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_records_source_record_id'), 'source_records', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_source_records_status'), 'source_records', ['status'], unique=False)
    op.create_index(op.f('ix_source_records_tenant_id'), 'source_records', ['tenant_id'], unique=False)
    op.create_table('provenance',
    sa.Column('provenance_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=True),
    sa.Column('processing_run_id', sa.String(length=64), nullable=True),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('rdkit_version', sa.String(length=32), nullable=False),
    sa.Column('normalization_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.run_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.source_record_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('provenance_id')
    )
    op.create_index(op.f('ix_provenance_processing_run_id'), 'provenance', ['processing_run_id'], unique=False)
    op.create_index(op.f('ix_provenance_source_record_id'), 'provenance', ['source_record_id'], unique=False)
    op.create_table('rejected_records',
    sa.Column('rejection_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=True),
    sa.Column('rejection_category', sa.String(length=64), nullable=False),
    sa.Column('raw_data_snippet', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('rdkit_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.source_record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rejection_id')
    )
    op.create_index(op.f('ix_rejected_records_rejection_category'), 'rejected_records', ['rejection_category'], unique=False)
    op.create_index(op.f('ix_rejected_records_source_record_id'), 'rejected_records', ['source_record_id'], unique=False)
    op.create_index('ix_rejection_cat_date', 'rejected_records', ['rejection_category', 'created_at'], unique=False)
    op.create_table('bioactivities',
    sa.Column('bioactivity_id', sa.String(length=64), nullable=False),
    sa.Column('compound_id', sa.String(length=64), nullable=False),
    sa.Column('assay_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=64), nullable=True),
    sa.Column('provenance_id', sa.String(length=64), nullable=True),
    sa.Column('is_experimental', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('original_relation', sa.String(length=16), nullable=True),
    sa.Column('original_value', sa.Float(), nullable=False),
    sa.Column('original_unit', sa.String(length=64), nullable=False),
    sa.Column('normalized_relation', sa.String(length=16), nullable=True),
    sa.Column('normalized_value', sa.Float(), nullable=False),
    sa.Column('normalized_unit', sa.String(length=64), nullable=False),
    sa.Column('p_activity', sa.Float(), nullable=True),
    sa.Column('p_activity_relation', sa.String(length=16), nullable=True),
    sa.Column('is_censored', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assay_id'], ['assays.assay_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compound_id'], ['compounds.compound_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provenance_id'], ['provenance.provenance_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.source_record_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('bioactivity_id')
    )
    op.create_index('ix_bioact_assay_type_norm', 'bioactivities', ['assay_id', 'activity_type', 'normalized_value'], unique=False)
    op.create_index('ix_bioact_comp_type_norm', 'bioactivities', ['compound_id', 'activity_type', 'normalized_value'], unique=False)
    op.create_index(op.f('ix_bioactivities_activity_type'), 'bioactivities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_bioactivities_assay_id'), 'bioactivities', ['assay_id'], unique=False)
    op.create_index(op.f('ix_bioactivities_bioactivity_id'), 'bioactivities', ['bioactivity_id'], unique=False)
    op.create_index(op.f('ix_bioactivities_compound_id'), 'bioactivities', ['compound_id'], unique=False)
    op.create_index(op.f('ix_bioactivities_is_censored'), 'bioactivities', ['is_censored'], unique=False)
    op.create_index(op.f('ix_bioactivities_is_experimental'), 'bioactivities', ['is_experimental'], unique=False)
    op.create_index(op.f('ix_bioactivities_normalized_value'), 'bioactivities', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_bioactivities_p_activity'), 'bioactivities', ['p_activity'], unique=False)
    op.create_index(op.f('ix_bioactivities_source_record_id'), 'bioactivities', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_bioactivities_tenant_id'), 'bioactivities', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bioactivities_tenant_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_source_record_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_p_activity'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_normalized_value'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_is_experimental'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_is_censored'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_compound_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_bioactivity_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_assay_id'), table_name='bioactivities')
    op.drop_index(op.f('ix_bioactivities_activity_type'), table_name='bioactivities')
    op.drop_index('ix_bioact_comp_type_norm', table_name='bioactivities')
    op.drop_index('ix_bioact_assay_type_norm', table_name='bioactivities')
    op.drop_table('bioactivities')
    op.drop_index('ix_rejection_cat_date', table_name='rejected_records')
    op.drop_index(op.f('ix_rejected_records_source_record_id'), table_name='rejected_records')
    op.drop_index(op.f('ix_rejected_records_rejection_category'), table_name='rejected_records')
    op.drop_table('rejected_records')
    op.drop_index(op.f('ix_provenance_source_record_id'), table_name='provenance')
    op.drop_index(op.f('ix_provenance_processing_run_id'), table_name='provenance')
    op.drop_table('provenance')
    op.drop_index(op.f('ix_source_records_tenant_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_status'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_record_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_source_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_external_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_dataset_id'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_content_hash'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_compound_id'), table_name='source_records')
    op.drop_index('ix_source_external_id', table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_processing_runs_dataset_id'), table_name='processing_runs')
    op.drop_table('processing_runs')
    op.drop_index(op.f('ix_assays_tenant_id'), table_name='assays')
    op.drop_index(op.f('ix_assays_target_id'), table_name='assays')
    op.drop_index(op.f('ix_assays_cell_line_id'), table_name='assays')
    op.drop_index(op.f('ix_assays_assay_type'), table_name='assays')
    op.drop_index(op.f('ix_assays_assay_id'), table_name='assays')
    op.drop_table('assays')
    op.drop_index(op.f('ix_targets_uniprot_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_target_name'), table_name='targets')
    op.drop_index(op.f('ix_targets_target_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_gene_symbol'), table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_molecular_features_tpsa'), table_name='molecular_features')
    op.drop_index(op.f('ix_molecular_features_clogp'), table_name='molecular_features')
    op.drop_table('molecular_features')
    op.drop_index(op.f('ix_datasets_tenant_id'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_source_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_identifier_type_value', table_name='compound_identifiers')
    op.drop_index(op.f('ix_compound_identifiers_tenant_id'), table_name='compound_identifiers')
    op.drop_index(op.f('ix_compound_identifiers_identifier_value'), table_name='compound_identifiers')
    op.drop_index(op.f('ix_compound_identifiers_identifier_type'), table_name='compound_identifiers')
    op.drop_index(op.f('ix_compound_identifiers_compound_id'), table_name='compound_identifiers')
    op.drop_table('compound_identifiers')
    op.drop_table('chemical_structures')
    op.drop_table('sources')
    op.drop_index(op.f('ix_organisms_scientific_name'), table_name='organisms')
    op.drop_table('organisms')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_compounds_tenant_id'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_murcko_scaffold_smiles'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_molecular_weight'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_molecular_formula'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_inchikey'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_has_stereochemistry'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_compound_id'), table_name='compounds')
    op.drop_index(op.f('ix_compounds_canonical_smiles'), table_name='compounds')
    op.drop_table('compounds')
    op.drop_index(op.f('ix_cell_lines_name'), table_name='cell_lines')
    op.drop_index(op.f('ix_cell_lines_cell_line_id'), table_name='cell_lines')
    op.drop_index(op.f('ix_cell_lines_cancer_type'), table_name='cell_lines')
    op.drop_table('cell_lines')
    # ### end Alembic commands ###
